name: events
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  nb_utils: ^6.0.6
  intl: ^0.18.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_countdown_timer: ^4.1.0

  #Database
  sqflite: ^2.3.0

  # State Management Technique
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
